[versions]
agp = "8.13.0"
calendar = "2.9.0"
composeCharts = "0.2.0"
espressoCore = "3.7.0"
junit = "4.13.2"
junitVersion = "1.3.0"
purchases = "9.12.1"
splashscreen = "1.0.1"
datastore = "1.2.0-beta01"
colorpicker = "1.1.2"
glance = "1.1.1"
koin = "4.1.1"
kotlin = "2.2.21"
ksp = "2.3.0"
material3 = "1.5.0-alpha07"
reorderable = "3.0.0"
room = "2.8.3"
navigation = "2.9.5"
serialization = "1.9.0"
materialKolor = "4.0.3"
aboutLibraries = "13.1.0"
composeIcons = "1.1.1"
compose = "1.9.4"
materialIconsExtended = "1.7.8"
biometric = "1.4.0-alpha02"
truth = "1.4.5"

[libraries]
# Android
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
androidx-datastore-preferences-core = { module = "androidx.datastore:datastore-preferences-core", version.ref = "datastore" }
androidx-glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "glance" }
androidx-glance-material3 = { module = "androidx.glance:glance-material3", version.ref = "glance" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splashscreen" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "room" }
androidx-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "compose" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
androidx-biometric = { group = "androidx.biometric", name = "biometric-ktx", version.ref = "biometric" }

# Others
junit = { module = "junit:junit", version.ref = "junit" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
purchases = { module = "com.revenuecat.purchases:purchases", version.ref = "purchases" }
purchases-ui = { module = "com.revenuecat.purchases:purchases-ui", version.ref = "purchases" }
reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }
materialKolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor" }
colorpicker-compose = { module = "com.github.skydoves:colorpicker-compose", version.ref = "colorpicker" }
aboutLibraries = { group = "com.mikepenz", name = "aboutlibraries-compose", version.ref = "aboutLibraries" }
aboutlibraries-compose-m3 = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutLibraries" }
composeIcons-fontAwesome = { module = "br.com.devsrsouza.compose.icons:font-awesome", version.ref = "composeIcons" }
calendar = { module = "com.kizitonwose.calendar:compose", version.ref = "calendar" }
compose-charts = { module = "io.github.ehsannarmani:compose-charts", version.ref = "composeCharts" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }

[plugins]
room = { id = "androidx.room", version.ref = "room" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
aboutLibraries = { id = "com.mikepenz.aboutlibraries.plugin.android", version.ref = "aboutLibraries" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }