[versions]
agp = "8.11.0"
calendar = "2.7.0"
composeCharts = "0.1.7"
splashscreen = "1.0.1"
datastore = "1.2.0-alpha02"
colorpicker = "1.1.2"
glance = "1.1.1"
koin = "4.1.0"
kotlin = "2.2.0"
ksp = "2.1.21-2.0.1"
material3 = "1.4.0-alpha16"
reorderable = "2.5.1"
room = "2.7.2"
sqlite = "2.5.2"
navigation = "2.9.0"
serialization = "1.8.1"
materialKolor = "2.1.1"
aboutLibraries = "12.2.4"
composeIcons = "1.1.1"
compose = "1.8.3"
materialIconsCore = "1.7.3"
biometric = "1.4.0-alpha02"

[libraries]
# Android
androidx-datastore-preferences-core = { module = "androidx.datastore:datastore-preferences-core", version.ref = "datastore" }
androidx-glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "glance" }
androidx-glance-material3 = { module = "androidx.glance:glance-material3", version.ref = "glance" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splashscreen" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
calendar = { module = "com.kizitonwose.calendar:compose", version.ref = "calendar" }
compose-charts = { module = "io.github.ehsannarmani:compose-charts", version.ref = "composeCharts" }
sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
androidx-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "compose" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
material-icons-core = { module = "org.jetbrains.compose.material:material-icons-core", version.ref = "materialIconsCore" }
androidx-biometric = { group = "androidx.biometric", name = "biometric-ktx", version.ref = "biometric" }

# Others
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }
materialKolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor" }
colorpicker-compose = { module = "com.github.skydoves:colorpicker-compose", version.ref = "colorpicker" }
aboutLibraries = { group = "com.mikepenz", name = "aboutlibraries-compose", version.ref = "aboutLibraries" }
aboutlibraries-compose-m3 = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutLibraries" }
composeIcons-fontAwesome = { module = "br.com.devsrsouza.compose.icons:font-awesome", version.ref = "composeIcons" }

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
aboutLibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutLibraries" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }