[versions]
agp = "8.13.1"
compileSdk = "36"
minSdk = "29"
targetSdk = "36"
calendar = "2.9.0"
compose-charts = "0.2.0"
espresso-core = "3.7.0"
junit = "4.13.2"
junit-version = "1.3.0"
kotlinx-datetime = "0.7.1"
purchases = "9.14.1"
splashscreen = "1.2.0"
datastore = "1.2.0"
colorpicker = "1.1.3"
glance = "1.1.1"
koin = "4.1.1"
kotlin = "2.2.21"
ksp = "2.3.0"
material3 = "1.10.0-alpha05"
reorderable = "3.0.0"
room = "2.8.4"
navigation = "2.9.1"
materialkolor = "4.0.4"
composeicons = "1.1.1"
compose = "1.9.5"
biometric = "1.4.0-alpha02"
truth = "1.4.5"
ktor = "3.3.2"
compose-multiplatform = "1.9.3"
compose-hot-reload = "1.0.0-rc04"
kotlinx-coroutines = "1.10.2"
kotlinx-rpc-krpc-client = "0.10.1"

[libraries]
# Android and compose stuff
compose-windowsizeclass = { module = "org.jetbrains.compose.material3:material3-window-size-class", version.ref = "material3" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junit-version" }
androidx-datastore-preferences-core = { module = "androidx.datastore:datastore-preferences-core", version.ref = "datastore" }
androidx-glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "glance" }
androidx-glance-material3 = { module = "androidx.glance:glance-material3", version.ref = "glance" }
material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splashscreen" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "room" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
navigation-compose = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
androidx-biometric = { group = "androidx.biometric", name = "biometric-ktx", version.ref = "biometric" }

# Server
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }

# Rpc
kotlinx-rpc-krpc-client = { module = "org.jetbrains.kotlinx:kotlinx-rpc-krpc-client", version.ref = "kotlinx-rpc-krpc-client" }
kotlinx-rpc-krpc-ktor-client = { module = "org.jetbrains.kotlinx:kotlinx-rpc-krpc-ktor-client", version.ref = "kotlinx-rpc-krpc-client" }
kotlinx-rpc-krpc-ktor-server = { module = "org.jetbrains.kotlinx:kotlinx-rpc-krpc-ktor-server", version.ref = "kotlinx-rpc-krpc-client" }
kotlinx-rpc-krpc-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-rpc-krpc-serialization-json", version.ref = "kotlinx-rpc-krpc-client" }
kotlinx-rpc-krpc-server = { module = "org.jetbrains.kotlinx:kotlinx-rpc-krpc-server", version.ref = "kotlinx-rpc-krpc-client" }

# Koin
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }

# Others
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
junit = { module = "junit:junit", version.ref = "junit" }
purchases = { module = "com.revenuecat.purchases:purchases", version.ref = "purchases" }
purchases-ui = { module = "com.revenuecat.purchases:purchases-ui", version.ref = "purchases" }
reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }
materialkolor = { module = "com.materialkolor:material-kolor", version.ref = "materialkolor" }
colorpicker-compose = { module = "com.github.skydoves:colorpicker-compose", version.ref = "colorpicker" }
composeicons-fontawesome = { module = "br.com.devsrsouza.compose.icons:font-awesome", version.ref = "composeicons" }
calendar = { module = "com.kizitonwose.calendar:compose-multiplatform", version.ref = "calendar" }
compose-charts = { module = "io.github.ehsannarmani:compose-charts", version.ref = "compose-charts" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }

[plugins]
kotlinx-rpc = { id = "org.jetbrains.kotlinx.rpc.plugin", version.ref = "kotlinx-rpc-krpc-client" }
room = { id = "androidx.room", version.ref = "room" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-hot-reload = { id = "org.jetbrains.compose.hot-reload", version.ref = "compose-hot-reload" }